variables:
  system.debug: 'false'
  lastCommitMessage: 'Upgrade beta version to 1.9.1 :zap:'
  pr.check.id: ''
  pr.status.id: ''
  MOBILECENTER_OUTPUT_DIRECTORY: $(Build.ArtifactStagingDirectory)/build
  MOBILECENTER_BRANCH: develop
  MOBILECENTER_BUILD_ID: $(Build.BuildNumber)
  MOBILECENTER_SOURCE_DIRECTORY: $(Build.Repository.LocalPath)
  MOBILECENTER_TRIGGER: continuous
  APPCENTER_OUTPUT_DIRECTORY: $(Build.ArtifactStagingDirectory)/build
  APPCENTER_BRANCH: develop
  APPCENTER_BUILD_ID: $(Build.BuildNumber)
  APPCENTER_SOURCE_DIRECTORY: $(Build.Repository.LocalPath)
  APPCENTER_TRIGGER: continuous
  artifactVersioning.build.format: timestamp
  buildScripts.toolset: '{"package.json":{"postClone":"appcenter-post-clone.sh"}}'
  javaScriptRunTests: 'false'
  MOBILECENTER_REACTNATIVE_PACKAGE: package.json
  APPCENTER_REACTNATIVE_PACKAGE: package.json
  SDK: ''
  TestSDK: iphonesimulator
  P12Filename: Certificates.p12
  CertificateType: apple distribution
  MobileProvisionFilename: Etendo_Mobile_Distribution.mobileprovision
  P12SecureFileId: ab637576-6255-4111-881f-9925ef484173
  MobileProvisionSecureFileId: 91218312-496d-4087-8815-289bd47446be
  AppExtensionProvisionSecureFiles: >-
    [{"fileId":"105406af-28ef-4246-8494-e1db2b52ab3e","fileName":"Etendo_Recieve_Share.mobileprovision","targetBundleIdentifier":"com.etendoapploader.ios.EtendoRecieveShare"}]
  MobileProvision: >-
    {"expirationDate":"2025-12-16T18:57:43.000Z","teamIdentifier":"B4T44MT553","type":"app-store","bundleIdentifier":"com.etendoapploader.ios","UUID":"9dcc02fc-0024-46fe-b528-5126536be0b3"}
  MOBILECENTER_XCODE_PROJECT: ios/Etendo_Mobile.xcworkspace
  MOBILECENTER_XCODE_SCHEME: Etendo_Mobile
  APPCENTER_XCODE_PROJECT: ios/Etendo_Mobile.xcworkspace
  APPCENTER_XCODE_WORKSPACE: ios/Etendo_Mobile.xcworkspace
  APPCENTER_XCODE_SCHEME: Etendo_Mobile
  SONOMA_API_SERVER: 'https://api.appcenter.ms'
  SONOMA_API_VERSION: v0.1
  VSMobileCenterUpload.ContinueIfSymbolsNotFound: 'true'
  destinationSubtype: apple
  sonoma.tags: 'continuous,javascript,xcode,signed,distribution'
  artifactVersioning.build.value: '0'
name: $(artifactVersioning.build.value)
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/develop
jobs:
  - job: Phase_1
    displayName: Build
    cancelTimeoutInMinutes: 0
    pool:
      name: Azure Pipelines
      vmImage: macOS-13
    steps:
      - checkout: self
        clean: true
        submodules: recursive
        lfs: true
      - task: PowerShell@2
        displayName: Install build scripts
        continueOnError: true
        inputs:
          targetType: inline
          scriptName: ''
          script: >-
            Set-Location -Path '$(Agent.HomeDirectory)'

            Invoke-WebRequest -Uri
            'https://build-assets.appcenter.ms/buildscripts/appcenter-build-assets-latest.zip'
            -OutFile 'appcenter-build-assets-latest.zip'

            if (Test-Path ./scripts) { Remove-Item -Path ./scripts -Force
            -Recurse }

            New-Item -ItemType directory -Path 'scripts' | Out-Null

            unzip -q -d 'scripts' 'appcenter-build-assets-latest.zip'

            Invoke-Expression 'bash ./scripts/init.sh'
          failOnStderr: true
      - task: ShellScript@2
        displayName: Post Clone Script
        inputs:
          scriptPath: appcenter-post-clone.sh
      - task: Bash@3
        displayName: Select Node.js Version v2
        inputs:
          filePath: $(Agent.HomeDirectory)/scripts/select-node-version.sh
          arguments: node18
          failOnStderr: true
      - task: CmdLine@1
        displayName: yarn/npm install
        inputs:
          filename: sh
          arguments: >-
            -c "if [ -f yarn.lock ]; then { yarn install
            --network-timeout=600000; } else npm install; fi"
      - task: CmdLine@2
        displayName: Generate source map
        inputs:
          script: >-
            #!/bin/sh

            INDEX_FILE="index.ios.js"

            if [ -f "index.js" ]; then
              INDEX_FILE="index.js"
            fi

            echo "Found $INDEX_FILE for ReactNative index."

            if [ ! -f ./node_modules/react-native/local-cli/cli.js ]; then
              mkdir ./node_modules/react-native/local-cli
             echo "require('@react-native-community/cli').run();" >> ./node_modules/react-native/local-cli/cli.js
            fi

            node --max_old_space_size=8192
            node_modules/react-native/local-cli/cli.js bundle --entry-file
            $INDEX_FILE --platform ios --dev false --reset-cache --bundle-output
            dummy-sourcemap-main.jsbundle --sourcemap-output index.ios.map
          failOnStandardError: false
      - task: CmdLine@1
        displayName: Copy source map file to staging
        inputs:
          filename: sh
          arguments: >-
            -c "mkdir -p $(build.artifactstagingdirectory)/symbols && cp
            index.ios.map $(build.artifactstagingdirectory)/symbols/"
          failOnStandardError: true
      - task: ShellScript@2
        displayName: Tag build
        inputs:
          scriptPath: $(Agent.HomeDirectory)/scripts/emit-tags.sh
          args: $(sonoma.tags)
      - task: CmdLine@1
        displayName: Set Xcode path
        inputs:
          filename: /bin/bash
          arguments: >-
            -c "sudo xcode-select --switch
            /Applications/Xcode_15.0.1.app/Contents/Developer"
      - task: InstallAppleCertificate@2
        displayName: Install Apple certificate
        inputs:
          certSecureFile: $(P12SecureFileId)
          certPwd: $(P12Password)
      - task: InstallAppleProvisioningProfile@0
        displayName: Install Apple provisioning profile
        inputs:
          provProfileSecureFile: $(MobileProvisionSecureFileId)
      - task: InstallAppleProvisioningProfile@0
        displayName: Install Apple provisioning profile
        inputs:
          provProfileSecureFile: 105406af-28ef-4246-8494-e1db2b52ab3e
      - task: CocoaPods@0
        displayName: Pod install
        inputs:
          cwd: ios
          forceRepoUpdate: true
      - task: Bash@3
        displayName: Determine project file path
        inputs:
          filePath: $(Agent.HomeDirectory)/scripts/detect-autogenerated-workspace.sh
          arguments: ios Etendo_Mobile
          workingDirectory: $(Build.SourcesDirectory)
      - task: ShellScript@2
        displayName: Determine signing style and pods update
        inputs:
          scriptPath: >-
            $(Agent.HomeDirectory)/scripts/determine-signing-style-and-pods-update.sh
          disableAutoCwd: true
          cwd: $(Build.SourcesDirectory)
      - task: PowerShell@2 
        displayName: Determine timestamp build numer
        inputs: 
          targetType: 'inline'
          script: |
            $timestamp = Get-Date -Format "yyyyMMddHH"
            $versionCode = [int]$timestamp
            Write-Host "##vso[task.setvariable variable=versionCode]$versionCode"
      - task: CmdLine@1
        displayName: Set Bundle version
        inputs:
          filename: /usr/bin/find
          arguments: >-
            . -name "*Info.plist" -exec /usr/libexec/PlistBuddy -c "Set
            :CFBundleVersion $(versionCode)" {} ;
      - task: CmdLine@1
        displayName: Update Xcode build settings
        continueOnError: true
        inputs:
          filename: node
          arguments: >-
            $(Agent.HomeDirectory)/scripts/build-xcproject-analyzer/node_modules/@build/xcproject-analyzer-script/script/bin.js
            --app-id="7c22e934-4599-477a-9f23-5c58b1500e79"
            --app-insights-key="$(AppInsightsKey)"
            --xc-workspace-path="$(APPCENTER_XCODE_WORKSPACE)"
            --scheme="Etendo_Mobile" --code-sign-style="$(SIGNING_OPTION)"
            --app-provisioning-profile-uuid="9dcc02fc-0024-46fe-b528-5126536be0b3"
            --app-extension-provisioning-profile-uuids="422a41d1-b62d-469e-b7d3-fd81030487bb"
            --app-extension-target-bundle-identifiers="com.etendoapploader.ios.EtendoRecieveShare"
            --code-sign-identity="$(APPLE_CERTIFICATE_SIGNING_IDENTITY)"
            --development-team="B4T44MT553"
            --app-bundle-identifier="com.etendoapploader.ios"
          workingFolder: $(Build.SourcesDirectory)
      - task: Xcode@4
        displayName: Xcode build (signed)
        inputs:
          actions: clean
          configuration: ''
          sdk: ''
          xcWorkspacePath: $(APPCENTER_XCODE_PROJECT)
          scheme: Etendo_Mobile
          xcodeDeveloperDir: /Applications/Xcode_15.0.1.app/Contents/Developer
          packageApp: true
          archivePath: $(agent.builddirectory)/output/build/archive
          exportPath: $(agent.builddirectory)/output/build/export
          signingOption: $(SIGNING_OPTION)
          outputPattern: $(agent.builddirectory)/output/build
      - task: CopyFiles@2
        displayName: Copy build files to staging
        inputs:
          SourceFolder: $(agent.builddirectory)/output/build/export
          Contents: '**/*.ipa'
          TargetFolder: $(build.artifactstagingdirectory)/build
          OverWrite: true
          flattenFolders: true
      - task: CopyFiles@2
        displayName: Copy symbol files to staging
        inputs:
          SourceFolder: >-
            $(agent.builddirectory)/output/build/archive/Etendo_Mobile.xcarchive/dSYMs
          Contents: '**/*.dSYM/**'
          TargetFolder: $(build.artifactstagingdirectory)/symbols
          OverWrite: true
      - task: PublishBuildArtifacts@1
        displayName: Publish build
        inputs:
          PathtoPublish: $(build.artifactstagingdirectory)/build
          ArtifactName: build
          TargetPath: \\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)
      - task: PublishBuildArtifacts@1
        displayName: Publish symbols
        continueOnError: true
        inputs:
          PathtoPublish: $(build.artifactstagingdirectory)/symbols
          ArtifactName: symbols
          TargetPath: \\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)
      - script: |
          echo "New version with updated features and compatibility improvements" > $(System.DefaultWorkingDirectory)/ReleaseNotes.txt
          echo "Please test compatibility with iOS 15+ and report any issues" > $(System.DefaultWorkingDirectory)/changelog.txt
        displayName: 'Create Release Notes and Changelog files'
      - task: AppStoreRelease@1
        inputs:
          serviceEndpoint: 'app center'
          releaseTrack: 'TestFlight'
          ipaPath: '$(build.artifactstagingdirectory)/build/*.ipa'
          appIdentifier: 'com.etendoapploader.ios'
          appType: 'iOS'
          appSpecificId: '6451114033'
          distributedToExternalTesters: true
          releaseNotes: '$(System.DefaultWorkingDirectory)/ReleaseNotes.txt'
          changelog: '$(System.DefaultWorkingDirectory)/changelog.txt'
          externalTestersGroups: 'external tester'
        displayName: 'Publish to TestFlight'
