variables:
  P12SecureFileId: ab637576-6255-4111-881f-9925ef484173
  MobileProvisionSecureFileId: 91218312-496d-4087-8815-289bd47446be
  AppExtensionProvisionSecureFiles: >-
    [{"fileId":"105406af-28ef-4246-8494-e1db2b52ab3e","fileName":"Etendo_Recieve_Share.mobileprovision","targetBundleIdentifier":"com.etendoapploader.ios.EtendoRecieveShare"}]
  MobileProvision: >-
    {"expirationDate":"2025-12-16T18:57:43.000Z","teamIdentifier":"B4T44MT553","type":"app-store","bundleIdentifier":"com.etendoapploader.ios","UUID":"9dcc02fc-0024-46fe-b528-5126536be0b3"}
  APPCENTER_XCODE_PROJECT: ios/Etendo_Mobile.xcworkspace
  APPCENTER_XCODE_WORKSPACE: ios/Etendo_Mobile.xcworkspace
  sonoma.tags: 'continuous,javascript,xcode,signed,distribution'
  artifactVersioning.build.value: '0'
  APPLE_CERTIFICATE_SIGNING_IDENTITY: 'Apple Distribution: FUTIT SERVICES SRL (B4T44MT553)'
  # NUEVAS VARIABLES PARA OPTIMIZACIÓN
  CCACHE_DIR: $(Pipeline.Workspace)/.ccache
  DERIVED_DATA_PATH: $(Agent.TempDirectory)/DerivedData
  
name: $(artifactVersioning.build.value)

resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/$(Build.SourceBranch)

pr: none

jobs:
  - job: Phase_1
    displayName: Build
    cancelTimeoutInMinutes: 0
    pool:
      name: Azure Pipelines
      vmImage: macOS-14
    
    steps:
      - checkout: self
        clean: false  # OPTIMIZACIÓN 1: No limpiar si no es necesario
        submodules: recursive
        lfs: true
        fetchDepth: 1  # OPTIMIZACIÓN 2: Shallow clone
      
      # OPTIMIZACIÓN 3: Cachear node_modules
      - task: Cache@2
        displayName: Cache node_modules
        inputs:
          key: 'npm | "$(Agent.OS)" | package-lock.json | package.json'
          path: node_modules
          restoreKeys: |
            npm | "$(Agent.OS)"
            npm
      
      # OPTIMIZACIÓN 4: Cachear Pods
      - task: Cache@2
        displayName: Cache CocoaPods
        inputs:
          key: 'pods | "$(Agent.OS)" | ios/Podfile.lock'
          path: ios/Pods
          restoreKeys: |
            pods | "$(Agent.OS)"
            pods
      
      # OPTIMIZACIÓN 5: Cachear ccache para compilación incremental
      - task: Cache@2
        displayName: Cache ccache
        inputs:
          key: 'ccache | "$(Agent.OS)" | "$(Build.SourceVersion)"'
          path: $(CCACHE_DIR)
          restoreKeys: |
            ccache | "$(Agent.OS)"
            ccache
      
      # OPTIMIZACIÓN 6: Cachear DerivedData
      - task: Cache@2
        displayName: Cache Xcode DerivedData
        inputs:
          key: 'deriveddata | "$(Agent.OS)" | ios/**/*.xcodeproj | ios/Podfile.lock'
          path: $(DERIVED_DATA_PATH)
          restoreKeys: |
            deriveddata | "$(Agent.OS)"
      
      - task: Bash@3
        displayName: Create scripts directory
        inputs:
          targetType: 'inline'
          script: |
            mkdir -p $(Agent.HomeDirectory)/scripts
            # Instalar ccache si no está disponible
            if ! command -v ccache &> /dev/null; then
              echo "Installing ccache..."
              brew install ccache
            fi
            ccache --max-size=5G
            ccache --set-config=compression=true
          failOnStderr: false
      
      - task: PowerShell@2
        displayName: Install build scripts
        continueOnError: true
        inputs:
          targetType: inline
          script: >-
            Set-Location -Path '$(Agent.HomeDirectory)'

            Invoke-WebRequest -Uri
            'https://build-assets.appcenter.ms/buildscripts/appcenter-build-assets-latest.zip'
            -OutFile 'appcenter-build-assets-latest.zip'

            if (Test-Path ./scripts) { Remove-Item -Path ./scripts -Force -Recurse }

            New-Item -ItemType directory -Path 'scripts' | Out-Null

            unzip -q -d 'scripts' 'appcenter-build-assets-latest.zip'

            Invoke-Expression 'bash ./scripts/init.sh'
          failOnStderr: false
      
      - task: ShellScript@2
        displayName: Post Clone Script
        condition: succeeded()
        inputs:
          scriptPath: appcenter-post-clone.sh
      
      - task: NodeTool@0
        displayName: 'Use Node 18.x'
        inputs:
          versionSpec: '18.x'
      
      # OPTIMIZACIÓN 7: Solo instalar si no hay caché
      - task: CmdLine@1
        displayName: yarn/npm install
        condition: ne(variables['CacheRestored-npm'], 'true')
        inputs:
          filename: sh
          arguments: >-
            -c "if [ -f yarn.lock ]; then { yarn install --frozen-lockfile --network-timeout=600000; } else npm ci; fi"
      
      # OPTIMIZACIÓN 8: Generar sourcemap solo en release final
      - task: CmdLine@2
        displayName: Generate source map
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        inputs:
          script: |
            #!/bin/sh
            INDEX_FILE="index.ios.js"
            if [ -f "index.js" ]; then
              INDEX_FILE="index.js"
            fi
            
            if [ ! -f ./node_modules/react-native/local-cli/cli.js ]; then
              mkdir -p ./node_modules/react-native/local-cli
              echo "require('@react-native-community/cli').run();" >> ./node_modules/react-native/local-cli/cli.js
            fi
            
            node --max_old_space_size=8192 node_modules/react-native/local-cli/cli.js bundle \
              --entry-file $INDEX_FILE \
              --platform ios \
              --dev false \
              --reset-cache \
              --bundle-output dummy-sourcemap-main.jsbundle \
              --sourcemap-output index.ios.map
          failOnStandardError: false
      
      - task: CmdLine@1
        displayName: Copy source map file to staging
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        inputs:
          filename: sh
          arguments: >-
            -c "mkdir -p $(build.artifactstagingdirectory)/symbols && cp index.ios.map $(build.artifactstagingdirectory)/symbols/"
      
      - task: Bash@3
        displayName: Tag build
        inputs:
          targetType: 'inline'
          script: |
            echo "##vso[build.addbuildtag]continuous"
            echo "##vso[build.addbuildtag]javascript"
            echo "##vso[build.addbuildtag]xcode"
            echo "##vso[build.addbuildtag]signed"
            echo "##vso[build.addbuildtag]distribution"
      
      - task: Bash@3
        displayName: "Select Xcode 16 (iOS 18 SDK)"
        inputs:
          targetType: 'inline'
          script: |
            XCODE_CANDIDATE=$(ls /Applications | grep -E '^(Xcode_16|Xcode 16)' | grep -vi beta | head -n 1)
            
            if [ -z "$XCODE_CANDIDATE" ]; then
              echo "ERROR: Xcode 16 not found"
              exit 1
            fi
            
            XCODE_PATH="/Applications/$XCODE_CANDIDATE/Contents/Developer"
            echo "##vso[task.setvariable variable=XCODE_DEVELOPER_DIR]$XCODE_PATH"
            sudo xcode-select -s "$XCODE_PATH"
            xcodebuild -version
      
      - task: InstallAppleCertificate@2
        displayName: Install Apple certificate
        inputs:
          certSecureFile: $(P12SecureFileId)
          certPwd: $(P12Password)
      
      - task: InstallAppleProvisioningProfile@0
        displayName: Install Apple provisioning profile
        inputs:
          provProfileSecureFile: $(MobileProvisionSecureFileId)
      
      - task: InstallAppleProvisioningProfile@0
        displayName: Install extension provisioning profile
        inputs:
          provProfileSecureFile: 105406af-28ef-4246-8494-e1db2b52ab3e
      
      - task: Bash@3
        displayName: Add Podfile post_install hook
        inputs:
          targetType: 'inline'
          script: |
            if [ -f "ios/Podfile" ]; then
              if ! grep -q "post_install" ios/Podfile; then
                cat >> ios/Podfile << 'EOF'
            
            post_install do |installer|
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                  config.build_settings['ENABLE_BITCODE'] = 'NO'
                  config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
                  # OPTIMIZACIÓN: Habilitar compilación en paralelo
                  config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = 'NO'
                end
              end
            end
            EOF
              fi
            fi
      
      - task: Bash@3
        displayName: Update iOS Deployment Target
        inputs:
          targetType: 'inline'
          script: |
            find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' {} \;
            
            if [ -f "ios/Podfile" ]; then
              sed -i '' "s/platform :ios, '11.0'/platform :ios, '12.0'/g" ios/Podfile
            fi
      
      # OPTIMIZACIÓN 9: Solo ejecutar pod install si no hay caché o si Podfile.lock cambió
      - task: CocoaPods@0
        displayName: Pod install
        condition: or(ne(variables['CacheRestored-pods'], 'true'), changed('ios/Podfile.lock'))
        inputs:
          cwd: ios
          forceRepoUpdate: false  # Cambiar a false para mayor velocidad
      
      - task: PowerShell@2
        displayName: Determine build number
        inputs: 
          targetType: 'inline'
          script: |
            $timestamp = Get-Date -Format "yyyyMMddHH"
            [long]$timestampValue = [long]$timestamp
            $increment = 1
            $buildIdRaw = $env:BUILD_BUILDID
            
            if (![string]::IsNullOrWhiteSpace($buildIdRaw)) {
              [long]$buildId = [long]$buildIdRaw
              $increment = (($buildId - 1) % 1000) + 1
            }
            
            $versionCode = $timestampValue + $increment
            Write-Host "##vso[task.setvariable variable=versionCode]$versionCode"
            Write-Host "##vso[task.setvariable variable=BUNDLE_VERSION]$versionCode"
      
      - task: CmdLine@1
        displayName: Set Bundle version
        inputs:
          filename: /usr/bin/find
          arguments: >-
            . -name "*Info.plist" -exec /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(versionCode)" {} ;
      
      # OPTIMIZACIÓN 10: Xcode build con configuraciones de rendimiento
      - task: Xcode@4
        displayName: Xcode build (optimized)
        inputs:
          actions: build  # CAMBIO: Remover 'clean' para build incremental
          configuration: Release
          sdk: iphoneos
          xcWorkspacePath: $(APPCENTER_XCODE_PROJECT)
          scheme: Etendo_Mobile
          xcodeDeveloperDir: $(XCODE_DEVELOPER_DIR)
          packageApp: true
          archivePath: $(agent.builddirectory)/output/build/archive
          exportPath: $(agent.builddirectory)/output/build/export
          signingOption: manual
          signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
          provisioningProfileUuid: '9dcc02fc-0024-46fe-b528-5126536be0b3'
          teamId: 'B4T44MT553'
          args: |
            -allowProvisioningUpdates
            -destination generic/platform=iOS
            -derivedDataPath $(DERIVED_DATA_PATH)
            -parallelizeTargets
            -jobs $(sysctl -n hw.ncpu)
            COMPILER_INDEX_STORE_ENABLE=NO
            ENABLE_BITCODE=NO
            DEBUG_INFORMATION_FORMAT=dwarf
            GCC_OPTIMIZATION_LEVEL=s
            SWIFT_OPTIMIZATION_LEVEL=-O
            SWIFT_COMPILATION_MODE=wholemodule
            CLANG_ENABLE_MODULE_DEBUGGING=NO
          outputPattern: $(agent.builddirectory)/output/build
          useXcpretty: true  # OPTIMIZACIÓN: Mejor formato de salida
        continueOnError: false
        timeoutInMinutes: 60
      
      - task: CopyFiles@2
        displayName: Copy build files to staging
        inputs:
          SourceFolder: $(agent.builddirectory)/output/build/export
          Contents: '**/*.ipa'
          TargetFolder: $(build.artifactstagingdirectory)/build
          flattenFolders: true
      
      - task: CopyFiles@2
        displayName: Copy symbol files to staging
        inputs:
          SourceFolder: $(agent.builddirectory)/output/build/archive/Etendo_Mobile.xcarchive/dSYMs
          Contents: '**/*.dSYM/**'
          TargetFolder: $(build.artifactstagingdirectory)/symbols
      
      - task: PublishBuildArtifacts@1
        displayName: Publish build
        inputs:
          PathtoPublish: $(build.artifactstagingdirectory)/build
          ArtifactName: build
      
      - task: PublishBuildArtifacts@1
        displayName: Publish symbols
        continueOnError: true
        inputs:
          PathtoPublish: $(build.artifactstagingdirectory)/symbols
          ArtifactName: symbols
      
      - script: |
          echo "New version with updated features" > $(System.DefaultWorkingDirectory)/ReleaseNotes.txt
        displayName: 'Create Release Notes'
      
      - task: AppStoreRelease@1
        inputs:
          serviceEndpoint: 'app center'
          releaseTrack: 'Production'
          ipaPath: '$(build.artifactstagingdirectory)/build/*.ipa'
          appIdentifier: 'com.etendoapploader.ios'
          appType: 'iOS'
          appSpecificId: '6451114033'
        displayName: 'Publish to App Store'